function styles(sheet, sv) {
  // Helper Classes
  sheet.add('.pull-right', `float:right`)

  sheet.add('body', `
    margin:0px;
    padding:0px;
    font-size:10px;
    font-family: "Noto Sans", "Noto Sans CJK JP", sans-serif;
    color:${sv.textColor};
  `)
  sheet.add('i:before', `
    color:${sv.textColor};
  `)
  sheet.add('button,h3', `
  font-weight:200;
  font-family: "Noto Sans", "Noto Sans CJK JP", sans-serif;
  border:0px;
  background:none;
`)
  sheet.add('button i', `
  font-size:2em;
`)
  sheet.add('h1', `
    font-weight:100;
    font-size:4em;
    color:${sv.textColor};
    font-weight:100;
    padding:0.5em;
    display:inline-block;
    margin: 0;
  `)
  sheet.add('h2', `
    ${sheet.extend('h1').css}
    font-size:1.5em;
    padding:0.5em;
    margin:0px;
  `)
  sheet.add('input', `
    margin:0px;
    padding:0px;
    border:0px;
    font-size:2em;
    font-weight:100;
    background:transparent;
    color:${sv.textColor};
  `)
  sheet.add('input:focus', `
   outline:none;
  `)
  sheet.add('.isCollapsed .marks', `
    height: 0em;
    overflow: hidden;
    transition: 0.3s all ease;
    min-height: 0px !important;
    max-height: 1em !important;
  `)
  sheet.add('.group.isCollapsed', `
    height: 0em;
    overflow: hidden;
    transition: 0.3s all ease;
    min-height: 0px !important;
    max-height: 1em !important;
  `)

  sheet.addSpecial(`
  /* Generated by Glyphter (http://www.glyphter.com) on  Mon Mar 27 2017*/
  @font-face {
      font-family: 'bazza';
      src: url('fonts/bazza.eot');
      src: url('fonts/bazza.eot?#iefix') format('embedded-opentype'),
          url('fonts/bazza.woff') format('woff'),
          url('fonts/bazza.ttf') format('truetype'),
          url('fonts/bazza.svg#bazza') format('svg');
      font-weight: normal;
      font-style: normal;
  }
  [class*='icon-']:before{
    display: inline-block;
    font-family: 'bazza';
    font-style: normal;
    font-weight: normal;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale
  }
  .icon-link:before{content:'\\0041';}
  .icon-group:before{content:'\\0042';}
  .icon-database:before{content:'\\0043';}
  .icon-folder-files:before{content:'\\0044';}
  .icon-folder:before{content:'\\0045';}
  .icon-present:before{content:'\\0046';}
  .icon-star:before{content:'\\0047';}
  .icon-like:before{content:'\\0048';}
  .icon-bookmark-sheet:before{content:'\\0049';}
  .icon-bookmark:before{content:'\\004a';}
  .icon-box:before{content:'\\004b';}
  .icon-no-eye:before{content:'\\004c';}
  .icon-close:before{content:'\\004d';}
  .icon-tick:before{content:'\\004e';}
  .icon-gem:before{content:'\\004f';}
  .icon-book:before{content:'\\0050';}
  .icon-add:before{content:'\\0051';}
`)

}
module.exports = styles
